# Generated by Django 5.2.3 on 2025-07-01 23:13
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from ..models.role import COMPANY_ADMIN, BLOG_ADMIN


def apply_migration(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    app_list = [
        'blog',
    ]

    content_type_list = ContentType.objects.filter(app_label__in=app_list).all()
    blog_type_list = ContentType.objects.filter(app_label='blog').all()

    company_admin_group, company_admin_group_created = Group.objects.get_or_create(name=COMPANY_ADMIN)

    blog_admin_group, blog_admin_group_created = Group.objects.get_or_create(name=BLOG_ADMIN)

    # company admin permissions
    for content_type in content_type_list:
        permissions = Permission.objects.filter(content_type__app_label=content_type.app_label,
                                                content_type__model=content_type.model)
        for permission in permissions:
            company_admin_group.permissions.add(permission)

    # blog admin permissions
    for content_type in blog_type_list:
        permissions = Permission.objects.filter(content_type__app_label=content_type.app_label,
                                                content_type__model=content_type.model)
        for permission in permissions:
            blog_admin_group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
